DROP DATABASE IF EXISTS CONCESSIONARIA;

CREATE DATABASE CONCESSIONARIA;
USE CONCESSIONARIA;



CREATE TABLE UTENTE(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(255) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
NOME VARCHAR(255) NOT NULL,
COGNOME VARCHAR(255) NOT NULL
)Engine='InnoDB';


CREATE TABLE VEICOLO(
ID INTEGER PRIMARY KEY , 
TITOLO VARCHAR(255) NOT NULL,
PREZZO INTEGER,
DESCRIZIONE NVARCHAR(4000),
IMMAGINE NVARCHAR(4000)
)Engine='InnoDB';


CREATE TABLE PREFERITI(
UTENTE VARCHAR(255),
VEICOLO INTEGER NOT NULL,
INDEX IDX_UTENTE(UTENTE),
INDEX IDX_VEICOLO(VEICOLO),
FOREIGN KEY(UTENTE) REFERENCES UTENTE(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(VEICOLO)REFERENCES VEICOLO(ID) ON DELETE CASCADE ON UPDATE CASCADE
/*PRIMARY KEY (UTENTE,VEICOLO)*/
)Engine='InnoDB';




CREATE TABLE COOKIES(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
HASH VARCHAR(255) NOT NULL,
UTENTE INTEGER NOT NULL,
EXPIRES BIGINT NOT NULL,
FOREIGN KEY(UTENTE) REFERENCES UTENTE(ID) ON DELETE CASCADE ON UPDATE CASCADE 
)Engine='InnoDB';



